### ISSUE TITLE
Embed link does not work for youtube video with video ID DrI2lUXL1no

### ISSUE THREAD

**Issue by shantanu-deriv** [0xbsec/yt-embed#2]
check out the youtube video https://www.youtube.com/watch?v=DrI2lUXL1no
for some reason the thumbnail preview for this video is not correct
https://yt-embed.herokuapp.com/embed?v=DrI2lUXL1no

**Comment by mhasbini** [comment]
I added a change in https://github.com/0xbsec/yt-embed/commit/351066318b421d4e4f7f68707e59bcb24dc76217 so that you'll be able to specify which image format you need:

https://yt-embed.herokuapp.com/embed?v=DrI2lUXL1no&img=0

List of formats: https://stackoverflow.com/questions/2068344/how-do-i-get-a-youtube-video-thumbnail-from-the-youtube-api
